#!/usr/bin/env bash
#The script is sed to display the contents of the file /etc/passwd; of which 
#only the username, user id and Home directory path for the user are displayed

while read -r line; do
    echo "$line" | cut -d ':' -f 1,3,6
done</etc/passwd

