#!/usr/bin/env bash
# The script uses a while loop to iterate through the string "Best School"
# 10 times while printing a Hi on a new line just after the 9th iteration

i=1
while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ]; then
	   echo "Hi"
	fi
	i=$((i+1))
done
