#!/usr/bin/env bash
#The script starts a while loop that will continue to iterate as long as the 
#value of the i variable is less than or equal to 20.Within the loop, a case statement 
#is used to check the value of counter(i). "bad luck from China" is been displayed for the 4th loop iteration,
# "bad luck from Japan" for the 9th loop iteration, and "bad luck from Italy" for the 17th loop iteration:

i=1

while [ $i -le 20 ]
do
  case $i in
    4)
      echo "4"
      echo "bad luck from China"
      ;;
    9)
      echo "9"
      echo "bad luck from Japan"
      ;;
    17)
      echo "17"
      echo "bad luck from Italy"
      ;;
    *)
      echo "$i"
      ;;
  esac
  
  ((i++))
done

