#!/usr/bin/env bash
# This is a bash script that can be used to Change localhost to 127.0.0.2
# and Change facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
